import type { RunLog, ExperimentResult, ExportOptions } from './types.js';
import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';

/**
 * Export a RunLog to JSON, Markdown, or HTML.
 */
export function exportRun(log: RunLog, options: ExportOptions, outputPath?: string): string {
  let content: string;
  const ext = options.format === 'html' ? '.html' : options.format === 'md' ? '.md' : '.json';

  if (options.format === 'json') {
    content = toJson(log, options);
  } else if (options.format === 'md') {
    content = toMarkdown(log, options);
  } else {
    content = toHtml(log, options);
  }

  if (outputPath) {
    mkdirSync(dirname(outputPath) || '.', { recursive: true });
    writeFileSync(outputPath, content);
    console.log(`[modelab] Exported to ${outputPath}`);
  }

  return content;
}

function toJson(log: RunLog, opts: ExportOptions): string {
  const data: Record<string, unknown> = {
    goalId: log.goalId,
    runId: log.runId,
    status: log.status,
    totalCostUsd: log.totalCostUsd,
    completedAt: log.completedAt,
  };

  if (opts.includeMetadata !== false) {
    (data as Record<string, unknown>).startedAt = log.startedAt;
  }

  if (opts.includeCost !== false) {
    (data as Record<string, unknown>).totalCostUsd = log.totalCostUsd;
  }

  if (opts.includeScores !== false) {
    (data as Record<string, unknown>).bestResult = log.bestResult;
    (data as Record<string, unknown>).allResults = log.allResults;
  }

  return JSON.stringify(data, null, 2);
}

function toMarkdown(log: RunLog, opts: ExportOptions): string {
  const lines: string[] = [];

  lines.push(`# Research Report — ${log.goalId}`);
  lines.push('');
  lines.push(`**Run ID:** \`${log.runId}\``);
  lines.push(`**Status:** ${statusEmoji(log.status)} ${log.status}`);
  lines.push(`**Total cost:** $${log.totalCostUsd.toFixed(4)}`);
  lines.push(`**Completed:** ${new Date(log.completedAt).toLocaleString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  if (opts.includeScores !== false && log.allResults.length > 0) {
    lines.push('## Results Summary');
    lines.push('');
    lines.push('| Arm | Score | Cost | Tokens | Duration |');
    lines.push('|-----|-------|------|--------|---------|');
    for (const r of log.allResults) {
      const cached = r.cached ? ' 🗃️' : '';
      lines.push(`| ${r.armId}${cached} | ${r.score ?? 'N/A'} | $${r.costUsd.toFixed(4)} | ${r.tokensUsed.input + r.tokensUsed.output} | ${(r.durationMs / 1000).toFixed(1)}s |`);
    }
    lines.push('');
  }

  if (log.bestResult) {
    lines.push('## Best Result');
    lines.push('');
    lines.push(`**Arm:** ${log.bestResult.armId}  **Score:** ${log.bestResult.score ?? 'N/A'}`);
    lines.push('');
    lines.push('```');
    lines.push(log.bestResult.output.slice(0, 2000));
    if (log.bestResult.output.length > 2000) lines.push('\n... (truncated)');
    lines.push('```');
    lines.push('');
  }

  for (let i = 0; i < log.allResults.length; i++) {
    const r = log.allResults[i];
    lines.push(`## ${r.armId} — Iteration ${r.iteration}`);
    lines.push('');
    if (opts.includeScores !== false) {
      lines.push(`**Score:** ${r.score ?? 'N/A'} | **Cost:** $${r.costUsd.toFixed(4)} | **Tokens:** ${r.tokensUsed.input + r.tokensUsed.output}${r.cached ? ' 🗃️ (cached)' : ''}`);
      lines.push('');
    }
    lines.push('```');
    lines.push(r.output.slice(0, 1500));
    if (r.output.length > 1500) lines.push('\n... (truncated)');
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [modelab](https://github.com/darks0l/modelab) 🌑*');

  return lines.join('\n');
}

function toHtml(log: RunLog, opts: ExportOptions): string {
  const dark = opts.theme === 'dark';
  const bg = dark ? '#0d1117' : '#ffffff';
  const text = dark ? '#e6edf3' : '#1f2328';
  const muted = dark ? '#7d8590' : '#656d76';
  const border = dark ? '#30363d' : '#d0d7de';
  const accent = '#58a6ff';
  const success = '#3fb950';
  const warning = '#d29922';

  let resultsHtml = '';
  for (const r of log.allResults) {
    const scoreColor = getScoreColor(r.score);
    const cached = r.cached ? '<span class="badge cached">cached</span>' : '';
    resultsHtml += `
    <div class="result-card">
      <div class="result-header">
        <strong>${escapeHtml(r.armId)}</strong>
        ${r.score !== null ? `<span class="score" style="color:${scoreColor}">${r.score}/10</span>` : ''}
        ${cached}
        <span class="meta">$${r.costUsd.toFixed(4)} · ${r.tokensUsed.input + r.tokensUsed.output} tokens</span>
      </div>
      <pre class="output">${escapeHtml(r.output.slice(0, 1000))}${r.output.length > 1000 ? '\n...' : ''}</pre>
    </div>`;
  }

  const bestScoreColor = log.bestResult ? getScoreColor(log.bestResult.score) : text;
  const statusColor = log.status.includes('quality') ? success : log.status.includes('budget') ? warning : muted;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>modelab report — ${log.goalId}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; background: ${bg}; color: ${text}; line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 2rem; }
  h1 { font-size: 1.5rem; margin-bottom: 1rem; }
  h2 { font-size: 1.1rem; margin: 1.5rem 0 0.75rem; border-bottom: 1px solid ${border}; padding-bottom: 0.25rem; }
  .meta-row { display: flex; gap: 1.5rem; flex-wrap: wrap; font-size: 0.875rem; color: ${muted}; margin-bottom: 1rem; }
  .meta-row span { display: flex; align-items: center; gap: 0.25rem; }
  .badge { background: ${accent}; color: #fff; font-size: 0.7rem; padding: 0.1rem 0.4rem; border-radius: 4px; }
  .badge.cached { background: ${warning}; }
  .result-card { border: 1px solid ${border}; border-radius: 8px; padding: 1rem; margin-bottom: 1rem; }
  .result-header { display: flex; align-items: center; gap: 0.75rem; flex-wrap: wrap; margin-bottom: 0.75rem; font-size: 0.875rem; }
  .score { font-weight: 700; font-size: 1rem; }
  .meta { color: ${muted}; }
  pre.output { background: ${dark ? '#161b22' : '#f6f8fa'}; padding: 0.75rem; border-radius: 6px; font-size: 0.8rem; overflow-x: auto; white-space: pre-wrap; word-break: break-word; }
  .footer { margin-top: 2rem; text-align: center; font-size: 0.75rem; color: ${muted}; }
</style>
</head>
<body>
<h1>🌑 modelab Research Report</h1>
<div class="meta-row">
  <span><strong>Run:</strong> ${log.runId.slice(0, 8)}</span>
  <span><strong>Status:</strong> <span style="color:${statusColor}">${log.status}</span></span>
  <span><strong>Cost:</strong> $${log.totalCostUsd.toFixed(4)}</span>
  <span><strong>Best score:</strong> <span style="color:${bestScoreColor}">${log.bestResult?.score ?? 'N/A'}</span></span>
</div>
<h2>Results</h2>
${resultsHtml}
<div class="footer">Generated by <a href="https://github.com/darks0l/modelab" style="color:${accent}">modelab</a> 🌑</div>
</body>
</html>`;
}

function statusEmoji(status: string): string {
  if (status.includes('quality')) return '✅';
  if (status.includes('budget')) return '💸';
  if (status === 'failed') return '❌';
  if (status === 'completed') return '🏁';
  return '⏳';
}

function getScoreColor(score: number | null): string {
  if (score === null) return 'inherit';
  if (score >= 8) return '#3fb950';
  if (score >= 5) return '#d29922';
  return '#f85149';
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
